### ISSUE TITLE
Center text tab

### ISSUE THREAD

**Issue by pwsandoval** [KevinSilvester/wezterm-config#1]
I took your config for the tabs as an example, but I see that the text is not centered, there is a space on the left, although I can't find the config for this, am I missing something?

 (&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;wslhost ~ btop ~/.c&nbsp;&nbsp;)
 &nbsp;&nbsp;&nbsp;^
 &nbsp;&nbsp;&nbsp;^
 this space is bigger than right

Example of your demo:

![wez2](https://user-images.githubusercontent.com/15174704/221396089-6665c4d4-ecca-4c5d-be2c-6c400c48804a.png)

_Maybe it's better appreciated when the tab doesn't have the unicode character on the right, like next..._

My term, same problem:

![wez](https://user-images.githubusercontent.com/15174704/221396044-c218640b-8ba3-4bf7-a6b2-c68af36221cb.png)
_On the left have more **padding or space** than right_

Thanks for your time, and excellent config!

**Comment by KevinSilvester** [comment]
Thanks for pointing this out. I never noticed until now.

Adding the extra space has made the padding somewhat more even.
But I noticed the circle glyph takes up more than 1 character cell in width compared to the other characters and glyphs.
So padding may appear uneven again when that is visible on screen.

If it's still bothering you can try swapping out the [character](https://github.com/KevinSilvester/wezterm-config/blob/8de51c474876b43c5368ac03cd103c967cb0906c/config/tab-title.lua#L9) with another glyph, but that would ultimately come down personal preferences. So I'll close the issue with that 😎.
