### ISSUE TITLE
error on windows 11

### ISSUE THREAD

**Issue by azinsharaf** [KevinSilvester/wezterm-config#10]
i am getting the following errors. Any advice?
```
❯ wezterm
09:21:04.426  ERROR  wgpu::backend::direct > Error in Adapter::request_device: Limit 'max_compute_workgroups_per_dimension' value 65535 is better than allowed 0
09:21:04.431  ERROR  wezterm_gui::frontend > Failed to create window: Requesting a device failed
```

**Comment by KevinSilvester** [comment]
Hi @azinsharaf 
I'm not able to recreate the issue on my end.

Have you tried running the config with one of the [nightly builds](https://wezfurlong.org/wezterm/install/windows.html#installing-on-windows) of Wezterm?
Cuz I the current stable release has some issues that are fixed in the nightly builds

**Comment by KevinSilvester** [comment]
Hey @azinsharaf
The errors you're getting are mentioned in this [wezterm issue](https://github.com/wez/wezterm/issues/4171)

And it seems to be tied with an [issue](https://github.com/gfx-rs/wgpu/issues/4242) that the `wgpu` crate has when rendering on some AMD cards.
WezTerm relies on this crate for rendering if the `front_end` option is set to `WebGpu`.

The latest nightly build uses a newer version of the crate which may have addressed this issue.
So if the nightly build can't run this config I think your best shot would in setting the [`front_end`](https://wezfurlong.org/wezterm/config/lua/config/front_end.html) option to `OpenGL` in the file `./config/appearance.lua`

https://github.com/KevinSilvester/wezterm-config/blob/961570cdc70bd117f72d67af883ae42809bba630/config/appearance.lua#L4-L9

To:
```lua
   front_end = 'OpenGL'
```

Hope this helps 😊

**Comment by azinsharaf** [comment]
yes, changing to `OpenGL` fixed it. quick question: does it mean that wezterm won't use gpu if we  set it to `opengl`?
thanks!

**Comment by KevinSilvester** [comment]
No really, wezterm will still use the GPU.

My understanding is that `OpenGL` is like a cross-platform abstraction layer to make it easier to work with the GPUs.
While the `wgpu` crate is more of a bare-metal approach.

`OpenGL` is technically the slower of the two options but the difference isn't even noticeable.
I just have it set to `WebGpu` cuz it's shiny new toy 😅
