### ISSUE TITLE
`fuzzy_description` is not a valid InputSelector field. 

### ISSUE THREAD

**Issue by Asthestarsfalll** [KevinSilvester/wezterm-config#11]
Thank you for your awesome configs! I encountered this error without making any changes. My wezterm version is `20230712-072601-f4abf8fd
`

**Comment by KevinSilvester** [comment]
Hi @Asthestarsfalll,

Version `20230712-072601-f4abf8fd` has a good number of bugs. I think what you're experiencing is one of them.

There is a new stable release [`20240127-113634-bbcac864`](https://github.com/wez/wezterm/releases/tag/20240127-113634-bbcac864) which seems to be running this config with no issues so far.

Try that out. It may have addressed the bug.

**Comment by KevinSilvester** [comment]
I take back what I said 😅.

The latest release has an issue where closing the last active pane on a window will cause the UI to hang unless you change tabs, which then somehow frees the UI.
Not sure why this is happening but I think you're better off using the latest `nightly version [20240128-202157-1e552d76]`

If you're on Windows and use `scoop`, I have a scoop bucket setup to make installation a bit easier
```
scoop bucket add kbucket https://github.com/KevinSilvester/scoop-bucket
scoop install wezterm-nightly
```

and on Mac you get it setup with `homebrew`
```
brew tap homebrew/cask-versions
brew install --cask wezterm-nightly
```

Hope this helps 😎.

**Comment by Asthestarsfalll** [comment]
Thank you for your reply! I solved this issue.
