### ISSUE TITLE
请教如何设置一个tab内激活的panel

### ISSUE THREAD

**Issue by imkratos** [KevinSilvester/wezterm-config#15]
<img width="1920" alt="image" src="https://github.com/KevinSilvester/wezterm-config/assets/3302461/e87b24f1-aeeb-4f69-a19d-9eda2571f7aa">

如图，我想设置为如果某个panel没激活的时候，也正常显示，不跟现在一样显示灰色，我看你的方案里是解决了这个问题的，但我没找到从哪里可以设置。

**Comment by KevinSilvester** [comment]
Hi @imkratos

You could get all panes to display normally by removing the `inactive_pane_hsb` option in `config/appearance.lua`.

<https://github.com/KevinSilvester/wezterm-config/blob/13e4107031f71f016c0ca44faca8c9b9f69392cc/config/appearance.lua#L52-L55>

Hope this helps 😎

**Comment by imkratos** [comment]
tks bro , it's working .~
