### ISSUE TITLE
How to set my own background image？

### ISSUE THREAD

**Issue by touero** [KevinSilvester/wezterm-config#17]
I tried to delete all png images in `backdrops`, and then put my own images into them, but it didn't work. I would like to ask if there are any requirements for image format, name, etc.

**Comment by touero** [comment]
Also, if I want to customize the theme based on this, how can I do it?

**Comment by KevinSilvester** [comment]
The only requirement for the images should be image file type. ([List of supported file types according to the docs](https://wezfurlong.org/wezterm/config/lua/config/background.html#source-definition)).

Could you try checking if the images can be loaded if the file path is manually set in `config/appearance.lua`
Try changing line 17 to something like this ` source = { File = wezterm.config_dir .. '/backdrops/IMAGE_FILE.png' }, `
<https://github.com/KevinSilvester/wezterm-config/blob/master/config/appearance.lua#L15-L19>

This is just to check if the images are renderable by WezTerm.

**Comment by KevinSilvester** [comment]
As for theme generator, that might bit tricky 😅.

The only way I see that working is by
- Creating a new utility that runs after the `BackDrops` utility
- Read the global variable `wezterm.GLOBAL.background` for image file path
- Passes file path to a separate program that can scan the image and output the colours of the image
- Parse the output of the said program and generate a new `colors` table

It's bit convoluted but that's the only way I see that working.
You'd have to find/make an image scanning program for this to work.
And you'd probably have a noticeable delay every time wezterm starts up if it has to sample images to generate a new colorscheme before starting up.

**Comment by touero** [comment]
thanks
