### ISSUE TITLE
a error happened in windows system

### ISSUE THREAD

**Issue by Create-Peace** [KevinSilvester/wezterm-config#18]
`
callback error
stack traceback:
        [C]: in metamethod 'index'
        C:\Users\shuhai\.config\wezterm/config\bindings.lua:93: in main chunk
        [C]: in function 'require'
        [string "C:\Users\shuhai\.config\wezterm\wezterm.lua"]:12: in main chunk
caused by: `InputSelector` is not a valid KeyAssignment variant.  There are
too many alternatives to list here; consult the documentation!
`

**Comment by KevinSilvester** [comment]
This is just a guess, but I think the version of wezterm on your machine is too old for this config.

`InputSelector` is feature in available after `20230408-112425-69ae8472 `. A quick update should resolve the issue.

**Comment by Create-Peace** [comment]
Thanks. After upgrading the version of Wezterm, this issue has been resolved.
