### ISSUE TITLE
3 pixel border and a little question

### ISSUE THREAD

**Issue by Lo263** [KevinSilvester/wezterm-config#23]
![Screenshot_2024-09-26_14_20_11](https://github.com/user-attachments/assets/6adc3855-0271-4b19-9ce7-f00790b702d1)
Hey I have two questions and an issue. First tanks a lot for your work. Very appreciated.
1) Is it possible to disable the 3 pixel border? Is it an issue? A feature?
2) Is is possible to set up easily a black background when I don't want to be distracted?) (SOLVED)
3) Should I change domains.lua and why ?(in two words I don't want to take too much of your time) (SOLVED)
Thanks a lot and sorry for being a noob

**Comment by Lo263** [comment]
this code works for question number two. It surely is improvable but its ok for now.

{
   key = [[b]],  -- Bind to 'l' for light grey
   mods = mod.SUPER,  -- Use SUPER + L for this action
   action = wezterm.action_callback(function(window, _pane)
      -- Temporarily set the background to light grey and remove the image
      window:set_config_overrides({
         colors = {
            background = "#000000",  -- Light grey background color
         },
         -- Disable or clear the background image
         background = {
            {
               source = { Color = "#000000" },  -- Replace the image with a solid color
            }
         },
      })
   end),
},

**Comment by Lo263** [comment]
Hey thank you,
All padding set to 0, there is still 1-3 pixel on the left  :'(
You have to look at the picture full screen to see it
![Screenshot_2024-09-26_23_39_54](https://github.com/user-attachments/assets/1f7dfcab-6fa6-40c4-98b2-f654acd79f89)

**Comment by KevinSilvester** [comment]
No worries
as a part of the `BackDrops` utils.

**Comment by Lo263** [comment]
I just updated and your b is cool. But my issue remains. Btw why would you ever put padding at the bottom?
On the top I understand even if I think I'll cut it too.

**Comment by KevinSilvester** [comment]
The bottom padding is there cuz I don't like the nvim statusline and the Windows taskbar being too close to each other when I'm in full screen 😅

**Comment by Lo263** [comment]
Its worse with the nightly. the pixel is also on top & botom
It's not that bad but.. :)
So you think it's on wezterm to solve?
![Screenshot_2024-09-27_01_22_08](https://github.com/user-attachments/assets/ffce7072-fac8-4761-ac21-5bc57a0bf8c9)

**Comment by KevinSilvester** [comment]
OK, I may have found the perfect solution to get rid of the borders.

https://github.com/KevinSilvester/wezterm-config/blob/347eca12a054e2b851289f0d04925c4d221c7020/config/appearance.lua#L21-L28

I'm still laughing at how obvious the fix was.
For some reason, it never occurred to me I could make the height and width of the layer more than 100% until now 😂.

I really hope this works otherwise I may have to raise the white flag on this issue 🏳️.

**Comment by Lo263** [comment]
IT WORKS !

Using 120 % is a little strange but if it works it's ok for me.
Let's close this issue with a big THANK YOU.
