### ISSUE TITLE
How do i stop the image from enlarging to fit the terminal?

### ISSUE THREAD

**Issue by ngomkhang134** [KevinSilvester/wezterm-config#29]
i want to see the whole image in the terminal, but it keeps enlarging to fit it.

**Comment by ngomkhang134** [comment]
and also how do i blur the background .

**Comment by KevinSilvester** [comment]
Hey @ngomkhang134, I think you should take a look at the [Layer Definintion](https://wezfurlong.org/wezterm/config/lua/config/background.html#layer-definition) options. It defines the how each of the background layers fit on the screen. Try the different options and see what works for you.

I don't know if blurring the background is possible.

**Comment by ngomkhang134** [comment]
i found it https://wezfurlong.org/wezterm/config/lua/config/win32_system_backdrop.html

but where should i paste it?

**Comment by KevinSilvester** [comment]
I think the best place would be in the `appearance.lua`.
Something like this

```lua
   -- background
   win32_system_backdrop = 'Acrylic', 
   background = {
      ... 
   }, 
```

**Comment by ngomkhang134** [comment]
it doesn't work on my windows laptop, what's it like on your end?

**Comment by KevinSilvester** [comment]
Just tried it now and it's not working for me either.
it's working on the title bar but not the rest of the terminal
