### ISSUE TITLE
How to change the color of status bar from white to black

### ISSUE THREAD

**Issue by suncunqian** [KevinSilvester/wezterm-config#35]
I am a newbie to WezTerm. After installing your configuration file, my status bar is white. Could you please tell me how to modify the configuration file to make the status bar black, just like in your picture?
My system is windows11
![PixPin_2024-11-19_01-04-04](https://github.com/user-attachments/assets/d49612e0-7bdc-4eef-96fe-7bc30ac393c6)

**Comment by S-H-Go** [comment]
This is my way. use `window_decorations = 'INTEGRATED_BUTTONS|RESIZE'`. This cancels the status bar
![image](https://github.com/user-attachments/assets/b73af2f7-9ccd-4954-86d1-f431a29857db)

**Comment by KevinSilvester** [comment]
Hey @suncunqian, the dark title bar is something controlled by the systems setting rather than Wezterm.

https://github.com/user-attachments/assets/98ea4a0b-3f47-4acf-b133-9ec6c568e23d

**Comment by suncunqian** [comment]
> Hey @suncunqian, the dark title bar is something controlled by the system settings rather than Wezterm.
> 
> Hope this helps 🙂
> 
>  2024-11-19.21-56-15.mp4

wow thx

**Comment by suncunqian** [comment]
> This is my way. use `window_decorations = 'INTEGRATED_BUTTONS|RESIZE'`. This cancels the status bar ![image](https://private-user-images.githubusercontent.com/73683678/387653306-b73af2f7-9ccd-4954-86d1-f431a29857db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMTg5OTMsIm5iZiI6MTczMjIxODY5MywicGF0aCI6Ii83MzY4MzY3OC8zODc2NTMzMDYtYjczYWYyZjctOWNjZC00OTU0LTg2ZDEtZjQzMWEyOTg1N2RiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE5NTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MGNlZTVkMTdmNWYyMTkyNzBkOWJmOWQ3MDQ5OWRlYTk4YjIyZjY0YThiNDgwODU1MjZjOWU0MjE4NjA2ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jaTAesTgBw6iIjByXNli4kUbogz8bzVYJGxomGkWunA)

good way thx
