### ISSUE TITLE
how to change the integrated_title_button_style

### ISSUE THREAD

**Issue by muxirr** [KevinSilvester/wezterm-config#41]
![PixPin_2024-12-30_21-16-38](https://github.com/user-attachments/assets/83ec08d1-4cb6-41b6-a8da-e7bb269f6e7d)
i try to config but it doesn't work

**Comment by KevinSilvester** [comment]
Hey @muxirr, the `integrated_title_button_style` option will only take effect if the fancy tab bar is enabled.

https://github.com/KevinSilvester/wezterm-config/blob/9088aded90d5dfaf08397e0160a495ad35502351/config/appearance.lua#L33

The problem with the fancy tab bar is that it limits your control in styling it and sometimes cuts off unseen output glyphs.

**Comment by muxirr** [comment]
thanks，it works
